# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\msys64\mingw64\bin\cmake.exe

# The command to remove a file.
RM = C:\msys64\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Salar\Documents\ShapeWars

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Salar\Documents\ShapeWars\build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	C:\msys64\mingw64\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\msys64\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Salar\Documents\ShapeWars\build\CMakeFiles C:\Users\Salar\Documents\ShapeWars\build\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Salar\Documents\ShapeWars\build\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ShapeWars

# Build rule for target.
ShapeWars: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 ShapeWars
.PHONY : ShapeWars

# fast build rule for target.
ShapeWars/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/build
.PHONY : ShapeWars/fast

src/Game.obj: src/Game.cpp.obj
.PHONY : src/Game.obj

# target to build an object file
src/Game.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/src/Game.cpp.obj
.PHONY : src/Game.cpp.obj

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/Menu.obj: src/Menu.cpp.obj
.PHONY : src/Menu.obj

# target to build an object file
src/Menu.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/src/Menu.cpp.obj
.PHONY : src/Menu.cpp.obj

src/Menu.i: src/Menu.cpp.i
.PHONY : src/Menu.i

# target to preprocess a source file
src/Menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/src/Menu.cpp.i
.PHONY : src/Menu.cpp.i

src/Menu.s: src/Menu.cpp.s
.PHONY : src/Menu.s

# target to generate assembly for a file
src/Menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/src/Menu.cpp.s
.PHONY : src/Menu.cpp.s

src/PowerUp.obj: src/PowerUp.cpp.obj
.PHONY : src/PowerUp.obj

# target to build an object file
src/PowerUp.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/src/PowerUp.cpp.obj
.PHONY : src/PowerUp.cpp.obj

src/PowerUp.i: src/PowerUp.cpp.i
.PHONY : src/PowerUp.i

# target to preprocess a source file
src/PowerUp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/src/PowerUp.cpp.i
.PHONY : src/PowerUp.cpp.i

src/PowerUp.s: src/PowerUp.cpp.s
.PHONY : src/PowerUp.s

# target to generate assembly for a file
src/PowerUp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/src/PowerUp.cpp.s
.PHONY : src/PowerUp.cpp.s

src/Shape.obj: src/Shape.cpp.obj
.PHONY : src/Shape.obj

# target to build an object file
src/Shape.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/src/Shape.cpp.obj
.PHONY : src/Shape.cpp.obj

src/Shape.i: src/Shape.cpp.i
.PHONY : src/Shape.i

# target to preprocess a source file
src/Shape.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/src/Shape.cpp.i
.PHONY : src/Shape.cpp.i

src/Shape.s: src/Shape.cpp.s
.PHONY : src/Shape.s

# target to generate assembly for a file
src/Shape.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/src/Shape.cpp.s
.PHONY : src/Shape.cpp.s

src/Utils.obj: src/Utils.cpp.obj
.PHONY : src/Utils.obj

# target to build an object file
src/Utils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/src/Utils.cpp.obj
.PHONY : src/Utils.cpp.obj

src/Utils.i: src/Utils.cpp.i
.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s
.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ShapeWars.dir\build.make CMakeFiles/ShapeWars.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... ShapeWars
	@echo ... src/Game.obj
	@echo ... src/Game.i
	@echo ... src/Game.s
	@echo ... src/Menu.obj
	@echo ... src/Menu.i
	@echo ... src/Menu.s
	@echo ... src/PowerUp.obj
	@echo ... src/PowerUp.i
	@echo ... src/PowerUp.s
	@echo ... src/Shape.obj
	@echo ... src/Shape.i
	@echo ... src/Shape.s
	@echo ... src/Utils.obj
	@echo ... src/Utils.i
	@echo ... src/Utils.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

